# Generated by Django 4.1.7 on 2023-03-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(max_length=20),
        ),
    ]
