# Generated by Django 4.1.7 on 2023-03-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, choices=[('no', 'no'), ('small', 'small'), ('medium', 'medium')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('self', 'self'), ('professional', 'professional'), ('online', 'online'), ('other', 'other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Types.user', 'user'), ('Types.mentor', 'mentor')], max_length=20),
        ),
    ]
