# Generated by Django 4.1.7 on 2023-03-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, choices=[('Types.no', 'no'), ('Types.small', 'small'), ('Types.medium', 'medium')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('Types.self', 'self'), ('Types.professional', 'professional'), ('Types.online', 'online'), ('Types.other', 'other')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Types.user', 'user'), ('Types.mentor', 'mentor')], default='Types.user', max_length=40),
        ),
    ]
