# Generated by Django 4.1.7 on 2023-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customuser_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='audience',
            field=models.CharField(blank=True, choices=[('Audience.no', 'no'), ('Audience.small', 'small'), ('Audience.medium', 'medium')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='experience',
            field=models.CharField(blank=True, choices=[('Experience.self', 'self'), ('Experience.professional', 'professional'), ('Experience.online', 'online'), ('Experience.other', 'other')], max_length=40, null=True),
        ),
    ]
